# action.yaml
name: 'Upload File to Sharepoint'
description: 'Upload one or more files in a directory to Sharepoint site using client ID'
inputs:
  file_path:
    description: 'Source file path (glob ok)'
    required: true
  site_name:
    description: 'Sharepoint site name (see README.md)'
    required: true
  host_name:
    description: 'Sharepoint host name (see README.md)'
    required: true
  upload_path:
    description: 'Target upload path (see README.md)'
    required: true
  tenant_id:
    description: 'Sharepoint tenant ID'
    required: true
  client_id:
    description: 'Sharepoint client ID'
    required: true
  client_secret:
    description: 'Sharepoint client secret'
    required: true
  max_retries:
    description: 'Max retries for upload'
    required: false
    default: '3'
  login_endpoint:
    description: 'Microsoft Online Login API Endpoint (see README.md)'
    required: false
    default: "login.microsoftonline.com"
  graph_endpoint:
    description: 'Microsoft Graph API Endpoint (see README.md)'
    required: false
    default: "graph.microsoft.com"
  pre_delete:
    description: 'Delete file before uploading it (if it exists)'
    required: false
    default: 'false'
outputs:
  return:
    description: 'Function output'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.send-file.outputs.return }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.site_name }}
    - ${{ inputs.host_name }}
    - ${{ inputs.tenant_id }}
    - ${{ inputs.client_id }}
    - ${{ inputs.client_secret }}
    - ${{ inputs.upload_path }}
    - ${{ inputs.file_path }}
    - ${{ inputs.max_retries }}
    - ${{ inputs.login_endpoint }}
    - ${{ inputs.graph_endpoint }}
    - ${{ inputs.pre_delete }}
